travis:
  secure:
    BINSTAR_TOKEN: Zu8RxJkpkGSbbO2N4cIiUc6QMxUbgcyLsG1eNekeg1q0AqKXKKHcietAFiMelnyuAAN5RM1RBSo2PzqVlZH3isF3I1ZFBAkC9FTdzADySmK0Wt+ybDKahgFbOujUbvYUEjiWv2AnTWnbPLgAMUUyXzvezwQ3c+CC3JkHOI0YsLP+ZrgRg3N13hKw9sg9ir0L+GaokMFuyUIbLDmrm65/GOYFx5KdhI9+wM2xYXtpU7NuotnTfe25dgVkA8gSNQz3MD91S2rtxe1jucStXsrwV2jPYSY5awO1rh20z7hwxCITpyLY6iWXZW8BkBXw3KYh0l+J15dyKSyj2aTkCmLkkaiiakJMLi8kZ8C/ZSR10PQBbwqOnpURbWuk7S2lVAdQg6qt9Wa1WNUgi10ysXbkyhYHwaw4mlgjYayJJTAjebZR8R4NqF4grmuXslwj50z9no1ES1hwSVYRVvLYxtsdQx9xLj2mJ3NntNfo+grZLjU5Y3TdnnfrFGYSZJAweEPWpLGgrRjW5xBn5wGEgIsh68P/KjGj/6THDOTIT9wGMJZcFeoP7NoMC0cZMhh+McJ/zhWV6oZ7CvUkUK3y4tSth9mbEQTjEETaX00YYE4RRi2KrDqFvcSRLvD1PiSPWqPTqbYQZwZ02WbZU9nOTRTiDdZVA472E3yOjLflo8iOVGA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
